#ifndef OBSERVATION_H
#define OBSERVATION_H

#include <vector>
using namespace std;

struct Observation{
    vector<float> features;
    vector<bool> actionMask;
};

/*
FEATURES
    PLAYER NUMBER
    NUMBER OF PLAYERS LEFT
    MAX HEALTH
    PLAYER 0 HEALTH
    PLAYER 0 CARDS IN DECK
    PLAYER 0 CARDS IN JAIL
    PLAYER 0 CARDS IN HAND
    PLAYER 1 HEALTH
    PLAYER 1 CARDS IN DECK
    PLAYER 1 CARDS IN JAIL
    PLAYER 1 CARDS IN HAND
    PLAYER 2 HEALTH
    PLAYER 2 CARDS IN DECK
    PLAYER 2 CARDS IN JAIL
    PLAYER 2 CARDS IN HAND
    PLAYER 3 HEALTH
    PLAYER 3 CARDS IN DECK
    PLAYER 3 CARDS IN JAIL
    PLAYER 3 CARDS IN HAND

ACTION MASK
    DO NOTHING (dead/war/infiltrating)
    (2) PLAYER SWAPS NOTHING
    (2) PLAYER SWAPS 2
    (2) PLAYER SWAPS 3
    (2) PLAYER SWAPS 4
    (2) PLAYER SWAPS 5
    (2) PLAYER SWAPS 6
    (2) PLAYER SWAPS 7
    (2) PLAYER SWAPS 8
    (2) PLAYER SWAPS 9
    (2) PLAYER SWAPS 10
    (2) PLAYER SWAPS 11
    (2) PLAYER SWAPS 12
    (2) PLAYER SWAPS 13
    PLAYER PLAYS 3 
    PLAYER PLAYS 4
    PLAYER PLAYS 5
    PLAYER PLAYS 6
    PLAYER PLAYS 7
    PLAYER PLAYS 8
    PLAYER PLAYS 9
    PLAYER PLAYS 10
    PLAYER PLAYS 11
    PLAYER PLAYS 12
    PLAYER PLAYS 13
    PLAYER PLAYS 2 ON PLAYER 0
    PLAYER PLAYS 2 ON PLAYER 1
    PLAYER PLAYS 2 ON PLAYER 2
    PLAYER PLAYS 2 ON PLAYER 3
  */ 

#endif