#ifndef OBSERVATION_H
#define OBSERVATION_H

#include <vector>
using namespace std;

struct Observation{
    vector<float> features;
    vector<bool> actionMask;
};

/*
FEATURES
    PLAYER NUMBER
    NUMBER OF PLAYERS LEFT
    MAX HEALTH
    PLAYER 0 HEALTH
    PLAYER 0 CARDS IN DECK
    PLAYER 0 CARDS IN JAIL
    PLAYER 0 CARDS IN HAND
    PLAYER 1 HEALTH
    PLAYER 1 CARDS IN DECK
    PLAYER 1 CARDS IN JAIL
    PLAYER 1 CARDS IN HAND
    PLAYER 2 HEALTH
    PLAYER 2 CARDS IN DECK
    PLAYER 2 CARDS IN JAIL
    PLAYER 2 CARDS IN HAND
    PLAYER 3 HEALTH
    PLAYER 3 CARDS IN DECK
    PLAYER 3 CARDS IN JAIL
    PLAYER 3 CARDS IN HAND
    WAR
    INFILTRATING
    INFILTRATED PLAYER
    CARD PULLED LOCATION
    

ACTION MASK
    0 = DO NOTHING (dead/war/infiltrating)
    1 = (2) PLAYER SWAPS NOTHING
    2 = (2) PLAYER SWAPS 2
    3 = (2) PLAYER SWAPS 3
    4 = (2) PLAYER SWAPS 4
    5 = (2) PLAYER SWAPS 5
    6 = (2) PLAYER SWAPS 6
    7 = (2) PLAYER SWAPS 7
    8 = (2) PLAYER SWAPS 8
    9 = (2) PLAYER SWAPS 9
    10 = (2) PLAYER SWAPS 10
    11 = (2) PLAYER SWAPS 11
    12 = (2) PLAYER SWAPS 12
    13 = (2) PLAYER SWAPS 13
    14 = PLAYER PLAYS 3 
    15 = PLAYER PLAYS 4
    16 = PLAYER PLAYS 5
    17 = PLAYER PLAYS 6
    18 = PLAYER PLAYS 7
    19 = PLAYER PLAYS 8
    20 = PLAYER PLAYS 9
    21 = PLAYER PLAYS 10
    22 = PLAYER PLAYS 11
    23 = PLAYER PLAYS 12
    24 = PLAYER PLAYS 13
    25 = PLAYER PLAYS 2 ON PLAYER 0
    26 = PLAYER PLAYS 2 ON PLAYER 1
    27 = PLAYER PLAYS 2 ON PLAYER 2
    28 = PLAYER PLAYS 2 ON PLAYER 3
  */ 

#endif